[package]
name = "edge-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-svc = "0.51"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
rmodbus = "0.8"

[build-dependencies]
embuild = "0.33"
