[package]
name = "cloud_mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
serialport = "4.6"
serde_json = "1.0"
influxdb2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
tokio-serial = "5.4"
tokio-util = { version = "0.7", features = ["codec"] }
